begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,raw_user_meta_data) values('10000000-0000-0000-0000-000000000001','{"provider_id":"9999","user_name":"forged"}');
insert into auth.identities(id,user_id,provider,provider_id,identity_data) values(gen_random_uuid(),'10000000-0000-0000-0000-000000000001','github','7001','{"sub":"7001","user_name":"verified-human"}');
insert into auth.sessions(id,user_id) values('50000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001');
insert into public.github_users(github_user_id,login,account_type) values(7001,'verified-human','User');
insert into public.organizations(github_account_id,slug,name) values(9001,'allowed','Allowed'),(9002,'other','Other');
insert into public.organization_memberships(organization_id,github_user_id)
 select o.id,u.id from public.organizations o cross join public.github_users u where o.slug='allowed';
select set_config('request.jwt.claims','{"sub":"10000000-0000-0000-0000-000000000001","role":"authenticated","session_id":"50000000-0000-0000-0000-000000000001"}',true);
set local role authenticated;
select is(public.get_signed_in_access()->>'githubUserId','7001','uses Auth identity not mutable user metadata');
select is(jsonb_array_length(public.get_signed_in_access()->'organizations'),1,'only previously authorized membership attached');
select is((select count(*) from public.organizations),1::bigint,'RLS restricts organization reads');
select is((select count(*) from public.organizations where slug='other'),0::bigint,'other organization invisible');
reset role;
select is((select count(*) from public.github_users where github_user_id=7001),1::bigint,'repeated sign-in does not duplicate identity');
select is((select count(*) from public.organization_memberships where auth_user_id='10000000-0000-0000-0000-000000000001'),1::bigint,'verified identity attaches existing membership');
update public.organization_memberships set active=false;
set local role authenticated;
select is(jsonb_array_length(public.get_signed_in_access()->'organizations'),0,'removed membership takes effect immediately');
select is((select count(*) from public.organizations),0::bigint,'RLS rejects revoked membership');
reset role;
update public.organization_memberships set active=true;
delete from auth.sessions;
set local role authenticated;
select throws_ok($$select public.get_signed_in_access()$$,'42501','session is not active','revoked session rejected despite remaining JWT lifetime');
select is((select count(*) from public.organizations),0::bigint,'revoked session cannot bypass via tables');
select is((select count(*) from public.organization_memberships),0::bigint,'revoked session cannot read membership');
reset role;
select ok(not has_function_privilege('anon','public.get_signed_in_access()','EXECUTE'),'anonymous access denied');
select * from finish();
rollback;
