begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id) values('10000000-0000-0000-0000-000000000001');
insert into auth.identities(id,user_id,provider,provider_id,identity_data) values(gen_random_uuid(),'10000000-0000-0000-0000-000000000001','github','7001','{"sub":"7001","user_name":"owner"}');
insert into auth.sessions(id,user_id) values('50000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001');
insert into public.github_users(github_user_id,login,account_type) values(7001,'owner','User');
insert into public.organizations(github_account_id,slug,name) values(9001,'allowed','Allowed'),(9002,'other','Other');
insert into public.github_installations(organization_id,github_installation_id,account_id,account_login,account_type,installed_at)
 select id,case when slug='allowed' then 8001 else 8002 end,github_account_id,slug,'Organization',now() from public.organizations;
insert into public.repositories(organization_id,installation_id,github_repository_id,owner,name,full_name)
 select organization_id,id,6001,'allowed','repo','allowed/repo' from public.github_installations where github_installation_id=8001;
select public.complete_team_access('10000000-0000-0000-0000-000000000001','50000000-0000-0000-0000-000000000001',8001,9001,false,false,6001);
select set_config('request.jwt.claims','{"sub":"10000000-0000-0000-0000-000000000001","role":"authenticated","session_id":"50000000-0000-0000-0000-000000000001"}',true);
set local role authenticated;
select is(public.get_product_api_input(8001,'2026-09')->'standings'->>'organizationId',(select id::text from public.organizations where slug='allowed'),'spectator can read own team');
select is(public.get_product_api_input(8001,'2026-09')->'health','null'::jsonb,'health is optional');
select is(public.get_product_api_input(8001,'2026-09',true)->'health'->>'organizationId',(select id::text from public.organizations where slug='allowed'),'health uses same authorized tenant');
select throws_ok($$select public.get_product_api_input(8002,'2026-09')$$,'PT403','access_denied','cross-tenant read denied');
select throws_ok($$select public.get_product_api_input(9999,'2026-09')$$,'PT403','access_denied','unknown installation indistinguishable from denied');
select throws_ok($$select public.get_product_api_input(8001,'wrong')$$,'PT400','invalid_request','invalid season rejected');
reset role;
update public.repositories set active=false;
set local role authenticated;
select throws_ok($$select public.get_product_api_input(8001,'2026-09')$$,'PT403','access_denied','removed collaborator proof denies data');
reset role;
update public.repositories set active=true;
update public.organization_memberships set installation_verified_until=now()-interval '1 second';
set local role authenticated;
select throws_ok($$select public.get_product_api_input(8001,'2026-09')$$,'PT403','access_denied','expired verification lease denies data');
reset role;
update public.organization_memberships set installation_verified_until=now()+interval '5 minutes',active=false;
set local role authenticated;
select throws_ok($$select public.get_product_api_input(8001,'2026-09')$$,'PT403','access_denied','local membership revocation denies data');
reset role;
update public.organization_memberships set active=true;
update public.github_installations set status='suspended' where github_installation_id=8001;
set local role authenticated;
select throws_ok($$select public.get_product_api_input(8001,'2026-09')$$,'PT403','access_denied','suspended installation denies data');
reset role;
update public.github_installations set status='active';
insert into public.github_users(github_user_id,login,account_type) select 10000+n,'person-'||n,'User' from generate_series(1,1001) n;
insert into public.participants(organization_id,github_user_id,display_name)
 select o.id,u.id,u.login from public.organizations o cross join public.github_users u where o.slug='allowed' and u.github_user_id>=10001;
set local role authenticated;
select throws_ok($$select public.get_product_api_input(8001,'2026-09')$$,'PT503','capacity_exceeded','oversized input fails explicitly rather than truncating totals');
reset role;
delete from auth.sessions;
set local role authenticated;
select throws_ok($$select public.get_product_api_input(8001,'2026-09')$$,'PT401','sign_in_again','revoked session denied despite JWT remaining lifetime');
reset role;
select ok(not has_function_privilege('anon','public.get_product_api_input(bigint,text,boolean)','EXECUTE'),'anonymous RPC denied');
select ok(not has_function_privilege('service_role','public.get_product_api_input(bigint,text,boolean)','EXECUTE'),'service cannot replace caller at this boundary');
select * from finish();
rollback;
