// @vitest-environment jsdom
import { act, cleanup, renderHook } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { REPLAY_STEP_MS, useSnapshotReplay } from './useSnapshotReplay'
const samples = [1, 2, 3].map(day => ({ sampledAt: `2026-09-0${day}T12:00:00Z`, totalPoints: day, participants: [] }))
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks() })
it('plays recorded samples once, stops on the last sample, and restarts from the first', () => {
 vi.useFakeTimers()
 const {result} = renderHook(() => useSnapshotReplay('season', samples))
 act(() => result.current.toggle())
 expect(result.current.sampledAt).toBe(samples[0]!.sampledAt)
 act(() => vi.advanceTimersByTime(REPLAY_STEP_MS))
 expect(result.current.sampledAt).toBe(samples[1]!.sampledAt)
 act(() => vi.advanceTimersByTime(REPLAY_STEP_MS))
 expect(result.current.sampledAt).toBe(samples[2]!.sampledAt)
 expect(result.current.playing).toBe(false)
 act(() => result.current.toggle())
 expect(result.current.sampledAt).toBe(samples[0]!.sampledAt)
 act(() => result.current.seek(null))
 expect(result.current.sampledAt).toBeNull()
 expect(result.current.playing).toBe(false)
})
it('pauses for manual scrubbing and a hidden tab; polling does not restart the sequence', () => {
 vi.useFakeTimers()
 const {result,rerender} = renderHook(({rows}) => useSnapshotReplay('season', rows), {initialProps:{rows:samples}})
 act(() => result.current.toggle())
 act(() => vi.advanceTimersByTime(REPLAY_STEP_MS / 2))
 rerender({rows:[...samples]})
 act(() => vi.advanceTimersByTime(REPLAY_STEP_MS / 2))
 expect(result.current.sampledAt).toBe(samples[1]!.sampledAt)
 act(() => result.current.seek(samples[0]!.sampledAt))
 act(() => vi.advanceTimersByTime(REPLAY_STEP_MS * 2))
 expect(result.current.sampledAt).toBe(samples[0]!.sampledAt)
 act(() => result.current.toggle())
 vi.spyOn(document,'visibilityState','get').mockReturnValue('hidden')
 act(() => document.dispatchEvent(new Event('visibilitychange')))
 expect(result.current.playing).toBe(false)
})
it('does not play empty or single-snapshot histories and resets effective state across seasons', () => {
 const {result,rerender} = renderHook(({season,rows}) => useSnapshotReplay(season,rows),{initialProps:{season:'one',rows:samples.slice(0,1)}})
 act(() => result.current.toggle())
 expect(result.current.playing).toBe(false)
 rerender({season:'one',rows:[]})
 expect(result.current.canPlay).toBe(false)
 rerender({season:'one',rows:samples})
 act(() => result.current.toggle())
 rerender({season:'two',rows:samples})
 expect(result.current.sampledAt).toBeNull()
 expect(result.current.playing).toBe(false)
})
