import type {
  Badge,
  Driver,
  DriverIdentity,
  DriverStanding,
  ReviewEvent,
  ReviewHealth,
  Season,
} from './types'

/**
 * Static mock data for the MVP. No API calls, no persistence — these constants
 * back every screen until real GitHub integration lands.
 */

export const drivers: Driver[] = [
  {
    id: 'drv-ada',
    name: 'Ada Sterling',
    code: 'ADA',
    number: 1,
    handle: 'adasterling',
    team: 'Velocity Works',
    color: '#3b82f6',
    flag: '🇬🇧',
  },
  {
    id: 'drv-mateo',
    name: 'Mateo Rivas',
    code: 'RIV',
    number: 11,
    handle: 'mateorivas',
    team: 'Apex Systems',
    color: '#ef4444',
    flag: '🇪🇸',
  },
  {
    id: 'drv-yuki',
    name: 'Yuki Tanaka',
    code: 'TAN',
    number: 22,
    handle: 'yukitanaka',
    team: 'Redline Labs',
    color: '#f59e0b',
    flag: '🇯🇵',
  },
  {
    id: 'drv-nadia',
    name: 'Nadia Okonkwo',
    code: 'OKO',
    number: 7,
    handle: 'nadiaok',
    team: 'Monsoon Tech',
    color: '#10b981',
    flag: '🇳🇬',
  },
  {
    id: 'drv-luca',
    name: 'Luca Bianchi',
    code: 'BIA',
    number: 16,
    handle: 'lucabianchi',
    team: 'Apex Systems',
    color: '#a855f7',
    flag: '🇮🇹',
  },
  {
    id: 'drv-priya',
    name: 'Priya Mehta',
    code: 'MEH',
    number: 4,
    handle: 'priyamehta',
    team: 'Velocity Works',
    color: '#ec4899',
    flag: '🇮🇳',
  },
]

export const season: Season = {
  id: 'season-2026-spring',
  name: '2026 Spring Championship',
  year: 2026,
  status: 'live',
  round: 4,
  totalRounds: 10,
  roundStartedAt: '2026-06-22T09:00:00Z',
  driverIds: drivers.map((d) => d.id),
}

export const standings: DriverStanding[] = [
  {
    driverId: 'drv-ada',
    position: 1,
    points: 286,
    reviews: 64,
    approvals: 41,
    delta: 0,
    gapToLeader: 0,
    fastestLap: false,
  },
  {
    driverId: 'drv-nadia',
    position: 2,
    points: 264,
    reviews: 58,
    approvals: 39,
    delta: 1,
    gapToLeader: 22,
    fastestLap: true,
  },
  {
    driverId: 'drv-mateo',
    position: 3,
    points: 251,
    reviews: 60,
    approvals: 33,
    delta: -1,
    gapToLeader: 35,
    fastestLap: false,
  },
  {
    driverId: 'drv-yuki',
    position: 4,
    points: 198,
    reviews: 47,
    approvals: 30,
    delta: 2,
    gapToLeader: 88,
    fastestLap: false,
  },
  {
    driverId: 'drv-priya',
    position: 5,
    points: 173,
    reviews: 44,
    approvals: 28,
    delta: 0,
    gapToLeader: 113,
    fastestLap: false,
  },
  {
    driverId: 'drv-luca',
    position: 6,
    points: 142,
    reviews: 39,
    approvals: 21,
    delta: -2,
    gapToLeader: 144,
    fastestLap: false,
  },
]

export const reviewEvents: ReviewEvent[] = [
  {
    id: 'evt-1001',
    driverId: 'drv-nadia',
    type: 'fastest-lap',
    pullNumber: 4821,
    pullTitle: 'fix: debounce search input on dashboard',
    points: 25,
    timestamp: '2026-06-25T14:32:00Z',
    turnaroundMinutes: 6,
  },
  {
    id: 'evt-1002',
    driverId: 'drv-ada',
    type: 'approve',
    pullNumber: 4819,
    pullTitle: 'feat: add driver stats endpoint',
    points: 15,
    timestamp: '2026-06-25T14:18:00Z',
    turnaroundMinutes: 22,
  },
  {
    id: 'evt-1003',
    driverId: 'drv-mateo',
    type: 'request-changes',
    pullNumber: 4815,
    pullTitle: 'refactor: extract timing tower component',
    points: 10,
    timestamp: '2026-06-25T13:55:00Z',
    turnaroundMinutes: 41,
  },
  {
    id: 'evt-1004',
    driverId: 'drv-ada',
    type: 'merge',
    pullNumber: 4810,
    pullTitle: 'chore: bump tanstack-router to 1.170',
    points: 20,
    timestamp: '2026-06-25T13:40:00Z',
  },
  {
    id: 'evt-1005',
    driverId: 'drv-yuki',
    type: 'comment',
    pullNumber: 4808,
    pullTitle: 'feat: race control toggle for live rounds',
    points: 5,
    timestamp: '2026-06-25T13:12:00Z',
    turnaroundMinutes: 18,
  },
  {
    id: 'evt-1006',
    driverId: 'drv-priya',
    type: 'approve',
    pullNumber: 4805,
    pullTitle: 'fix: track map viewBox on mobile',
    points: 15,
    timestamp: '2026-06-25T12:47:00Z',
    turnaroundMinutes: 33,
  },
  {
    id: 'evt-1007',
    driverId: 'drv-luca',
    type: 'comment',
    pullNumber: 4801,
    pullTitle: 'docs: season scoring rules',
    points: 5,
    timestamp: '2026-06-25T12:20:00Z',
    turnaroundMinutes: 52,
  },
  {
    id: 'evt-1008',
    driverId: 'drv-nadia',
    type: 'approve',
    pullNumber: 4799,
    pullTitle: 'feat: standings delta indicators',
    points: 15,
    timestamp: '2026-06-25T11:58:00Z',
    turnaroundMinutes: 14,
  },
]

/** Race Control — the team's PR-review health, used by the right-side panel. */
export const reviewHealth: ReviewHealth = {
  conditions: {
    reviewVelocity: 8.4,
    velocityTrend: 'cooling',
    teamTemperature: 'Focused',
    signal: 'yellow',
  },
  control: {
    uniqueReviewers: 5,
    prsNeedingReview: 7,
    prsWaitingOver24h: 2,
    mostUnderReviewedRepo: 'pull-prix/api',
  },
  nextReview: {
    repo: 'pull-prix/api',
    pullNumber: 4823,
    title: 'feat: review-health aggregation endpoint',
    waiting: '31h',
    reason: 'aging PR',
  },
}

/**
 * Collectible badge catalog. Each is earned through review behaviour; rarity is
 * purely cosmetic and drives the badge's glow/framing. Mocked — no unlock logic.
 */
export const BADGES = {
  polePosition: {
    id: 'pole-position',
    icon: '🏁',
    name: 'Pole Position',
    rarity: 'legendary',
    unlockedDate: '2026-06-21',
    description: 'Held P1 in the championship for a full race week.',
  },
  heatCheck: {
    id: 'heat-check',
    icon: '🔥',
    name: 'Heat Check',
    rarity: 'epic',
    unlockedDate: '2026-06-19',
    description: 'Reviewed on 10 consecutive days.',
  },
  bugHunter: {
    id: 'bug-hunter',
    icon: '🧠',
    name: 'Bug Hunter',
    rarity: 'epic',
    unlockedDate: '2026-06-12',
    description: 'Caught 25 bugs before they shipped.',
  },
  lightningReview: {
    id: 'lightning-review',
    icon: '⚡',
    name: 'Lightning Review',
    rarity: 'rare',
    unlockedDate: '2026-06-09',
    description: 'Turned around a review in under 10 minutes.',
  },
  refactorHero: {
    id: 'refactor-hero',
    icon: '🛠',
    name: 'Refactor Hero',
    rarity: 'rare',
    unlockedDate: '2026-05-30',
    description: 'Approved 15 refactors that reduced net lines of code.',
  },
  crossTeamRover: {
    id: 'cross-team-rover',
    icon: '🛰',
    name: 'Cross-Team Rover',
    rarity: 'rare',
    unlockedDate: '2026-05-22',
    description: 'Reviewed PRs across 5 different repositories.',
  },
  cleanupCrew: {
    id: 'cleanup-crew',
    icon: '🧹',
    name: 'Cleanup Crew',
    rarity: 'common',
    unlockedDate: '2026-05-15',
    description: 'Closed 20 stale or abandoned pull requests.',
  },
  testPilot: {
    id: 'test-pilot',
    icon: '🧪',
    name: 'Test Pilot',
    rarity: 'common',
    unlockedDate: '2026-05-08',
    description: 'Requested tests on 30 PRs that lacked coverage.',
  },
  constructorsChoice: {
    id: 'constructors-choice',
    icon: '👑',
    name: "Constructor's Choice",
    rarity: 'legendary',
    unlockedDate: '2026-06-01',
    description: 'Voted most valuable reviewer by the team.',
  },
} satisfies Record<string, Badge>

/** Full racing profile per driver. Selecting any driver shows a real profile. */
export const driverIdentities: Record<string, DriverIdentity> = {
  'drv-ada': {
    driverId: 'drv-ada',
    title: 'Apex Predator',
    topSpeed: 221,
    currentStreak: 12,
    bestStreak: 18,
    favoriteRepo: 'pull-prix/web',
    reviewsThisSeason: 64,
    avgReviewDepth: 4.8,
    avgResponseTime: '38m',
    badges: [
      BADGES.polePosition,
      BADGES.constructorsChoice,
      BADGES.heatCheck,
      BADGES.bugHunter,
      BADGES.lightningReview,
    ],
  },
  'drv-nadia': {
    driverId: 'drv-nadia',
    title: 'Lightning Hands',
    topSpeed: 218,
    currentStreak: 9,
    bestStreak: 14,
    favoriteRepo: 'pull-prix/api',
    reviewsThisSeason: 58,
    avgReviewDepth: 3.9,
    avgResponseTime: '14m',
    badges: [BADGES.lightningReview, BADGES.heatCheck, BADGES.crossTeamRover],
  },
  'drv-mateo': {
    driverId: 'drv-mateo',
    title: 'The Inspector',
    topSpeed: 209,
    currentStreak: 5,
    bestStreak: 11,
    favoriteRepo: 'pull-prix/infra',
    reviewsThisSeason: 60,
    avgReviewDepth: 6.2,
    avgResponseTime: '41m',
    badges: [BADGES.bugHunter, BADGES.testPilot, BADGES.refactorHero],
  },
  'drv-yuki': {
    driverId: 'drv-yuki',
    title: 'Steady Hand',
    topSpeed: 204,
    currentStreak: 7,
    bestStreak: 10,
    favoriteRepo: 'pull-prix/mobile',
    reviewsThisSeason: 47,
    avgReviewDepth: 4.1,
    avgResponseTime: '52m',
    badges: [BADGES.refactorHero, BADGES.cleanupCrew],
  },
  'drv-priya': {
    driverId: 'drv-priya',
    title: 'Range Rover',
    topSpeed: 201,
    currentStreak: 0,
    bestStreak: 8,
    favoriteRepo: 'pull-prix/design-system',
    reviewsThisSeason: 44,
    avgReviewDepth: 3.4,
    avgResponseTime: '1h 6m',
    badges: [BADGES.crossTeamRover, BADGES.cleanupCrew, BADGES.testPilot],
  },
  'drv-luca': {
    driverId: 'drv-luca',
    title: 'Rookie Charger',
    topSpeed: 198,
    currentStreak: 3,
    bestStreak: 6,
    favoriteRepo: 'pull-prix/docs',
    reviewsThisSeason: 39,
    avgReviewDepth: 2.9,
    avgResponseTime: '1h 24m',
    badges: [BADGES.testPilot],
  },
}
