import {describe,it,expect,vi} from 'vitest'
import {createAuthSessionHandler} from './handler.ts'
const config={supabaseUrl:'https://db.test',apiKey:'server-key',appOrigin:'https://app.test'}
const req=(body:unknown,origin='https://app.test')=>new Request('https://edge.test',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)})
describe('auth session boundary',()=>{
 it('exchanges PKCE while stripping every provider token and metadata field',async()=>{const fetcher=vi.fn().mockResolvedValue(Response.json({access_token:'app-token',refresh_token:'app-refresh',expires_in:3600,provider_token:'github-secret',provider_refresh_token:'github-refresh',user:{secret:'metadata'}}));const response=await createAuthSessionHandler(config,fetcher)(req({action:'exchange',code:'code',verifier:'a'.repeat(43)}));expect(response.status).toBe(200);const text=await response.text();expect(text).toContain('app-token');expect(text).not.toContain('github');expect(text).not.toContain('metadata');expect(response.headers.get('cache-control')).toBe('no-store');expect(fetcher.mock.calls[0]![0]).toContain('grant_type=pkce')})
 it('rejects other origins before exchange',async()=>{const fetcher=vi.fn();expect((await createAuthSessionHandler(config,fetcher)(req({action:'refresh',refreshToken:'r'},'https://other.test'))).status).toBe(403);expect(fetcher).not.toHaveBeenCalled()})
 it('does not echo provider errors or token values',async()=>{const fetcher=vi.fn().mockResolvedValue(Response.json({error:'secret'}, {status:400}));const r=await createAuthSessionHandler(config,fetcher)(req({action:'refresh',refreshToken:'r'}));expect(r.status).toBe(401);expect(await r.text()).not.toContain('secret')})
 it('requires valid verifier and an authenticated logout',async()=>{const handler=createAuthSessionHandler(config,vi.fn());expect((await handler(req({action:'exchange',code:'c',verifier:'short'}))).status).toBe(400);expect((await handler(req({action:'logout'}))).status).toBe(401)})
 it('uses local-session logout with the callers app token',async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(null,{status:204}));const r=req({action:'logout'});r.headers.set('authorization','Bearer app-token');expect((await createAuthSessionHandler(config,fetcher)(r)).status).toBe(200);expect(fetcher.mock.calls[0]![1].headers.authorization).toBe('Bearer app-token')})
})
