import { describe, expect, it } from "vitest"
import { calculateReviewHealth, type HealthInput } from "./v1.ts"
function fixture():HealthInput {return {organizationId:"org",eligibleFrom:"2026-09-07T12:00:00Z",coverageFrom:"2026-08-01T00:00:00Z",pendingPullRequests:0,
  participants:Array.from({length:6},(_,i)=>({id:String(i),eligible:true,active:true,joinedAt:"2026-08-01T00:00:00Z",leftAt:null})),reviews:[],pullRequests:[],dailyQueue:[]}}
const review=(id:string,participantId="0",at="2026-09-20T12:00:00Z",pr=id):HealthInput["reviews"][number]=>({id,participantId,pullRequestId:pr,organizationId:"org",occurredAt:at,readyAt:"2026-09-20T00:00:00Z"})
const pr=(id:string):HealthInput["pullRequests"][number]=>({id,organizationId:"org",open:true,draft:false,selected:true,authorEligible:true,readyAt:"2026-09-26T12:00:00Z",waitingForAuthor:false})
const run=(input:HealthInput,at="2026-09-28T12:00:00Z")=>calculateReviewHealth(input,at)
describe("PP-043 review health",()=>{
 it("counts useful pairs once and computes participation, spread and shares",()=>{const i=fixture();i.reviews=[review("a"),review("b"),review("c","1"),review("d","2"),review("dupe","0",undefined,"a")];const m=run(i).current!;expect(m.usefulReviews).toBe(4);expect(m.participation).toEqual({reviewers:3,roster:6,percentage:50});expect(m.loadSpreadPercentage).toBe(25);expect(m.individualShare.reduce((s,p)=>s+p.percentage!,0)).toBe(100)})
 it("omits load spread for small teams and empty work",()=>{const i=fixture();expect(run(i).current!.loadSpreadPercentage).toBeNull();i.participants.pop();i.reviews=[review("a")];expect(run(i).current!.loadSpreadPercentage).toBeNull()})
 it("uses median of each PR's first useful review, including already-closed PRs",()=>{const i=fixture();i.reviews=[review("a","0","2026-09-20T02:00:00Z"),review("b","1","2026-09-20T04:00:00Z"),review("later","2","2026-09-20T20:00:00Z","a")];expect(run(i).current!.medianFirstReviewMs).toBe(3*3600000);expect(run(i).current!.firstReviewSamples).toBe(2)})
 it("does not count a second reviewer as the PR's first in a later window",()=>{const i=fixture();i.reviews=[review("old","0","2026-09-06T14:00:00Z","pr"),review("new","1",undefined,"pr")];expect(run(i).current!.medianFirstReviewMs).toBeNull()})
 it("uses strict 24-hour aging and excludes drafts, closed, bots, unselected and author-waiting PRs",()=>{const i=fixture();i.pullRequests=[pr("yes"),{...pr("exact"),readyAt:"2026-09-27T12:00:00Z"},{...pr("draft"),draft:true},{...pr("closed"),open:false},{...pr("bot"),authorEligible:false},{...pr("removed"),selected:false},{...pr("author"),waitingForAuthor:true},pr("reviewed")];i.reviews=[review("r","0",undefined,"reviewed")];expect(run(i).agingQueue.pullRequestIds).toEqual(["yes"])})
 it("exposes unknown readiness rather than inventing age",()=>{const i=fixture();i.pullRequests=[{...pr("unknown"),readyAt:null}];expect(run(i)).toMatchObject({status:"partial",agingQueue:{count:0,unknownReadiness:["unknown"]}})})
 it("uses complete UTC days for baseline and seven-day trend",()=>{const i=fixture();i.reviews=[review("in","0","2026-09-21T00:00:00Z"),review("out","1","2026-09-28T00:00:00Z")];const m=run(i);expect(m.recent!.usefulReviews).toBe(1);expect(m.recent!.weeklyRate).toBe(1);expect(m.baseline!.startsAt).toBe("2026-08-08T00:00:00.000Z");expect(m.baseline!.endsAt).toBe("2026-09-07T00:00:00.000Z")})
 it("does not fabricate missing historical baseline or trend",()=>{const i=fixture();i.coverageFrom="2026-09-25T00:00:00Z";expect(run(i).baseline).toBeNull();expect(run(i).recent).toBeNull();expect(run(i).current).not.toBeNull()})
 it("uses entry roster for baseline and current roster for participation",()=>{const i=fixture();i.participants[5]!.joinedAt="2026-09-25T00:00:00Z";expect(run(i).baseline!.participation.roster).toBe(5);expect(run(i).current!.participation.roster).toBe(6)})
 it("excludes ineligible participants and future work",()=>{const i=fixture();i.participants[0]!.eligible=false;i.reviews=[review("excluded"),review("future","1","2026-09-29T00:00:00Z")];expect(run(i).current!.usefulReviews).toBe(0)})
 it("averages only complete daily snapshots and never fills missing days with zero",()=>{const i=fixture();i.dailyQueue=Array.from({length:7},(_,d)=>({day:`2026-09-${21+d}`,count:d}));expect(run(i).recent!.averageDailyAgingQueue).toBe(3);i.dailyQueue.pop();expect(run(i).recent!.averageDailyAgingQueue).toBeNull()})
 it("normalizes baseline counts to seven days",()=>{const i=fixture();i.reviews=Array.from({length:30},(_,d)=>review(String(d),"0","2026-08-20T00:00:00Z"));expect(run(i).baseline!.weeklyRate).toBe(7)})
 it("rejects cross-organization data and timezone-less clocks",()=>{const i=fixture();i.reviews=[{...review("bad"),organizationId:"other"}];expect(()=>run(i)).toThrow("Cross-organization");i.reviews=[];i.pullRequests=[{...pr("bad"),organizationId:"other"}];expect(()=>run(i)).toThrow("Cross-organization");expect(()=>run(fixture(),"2026-09-28T12:00:00")).toThrow("zoned")})
 it("keeps comparisons unavailable while eligibility history is unresolved",()=>{const i=fixture();i.pendingPullRequests=1;i.reviews=[review("a")];expect(run(i)).toMatchObject({status:"partial",baseline:null,recent:null});expect(run(i).current!.usefulReviews).toBe(1)})
 it("handles empty teams without division by zero",()=>{const i=fixture();i.participants=[];expect(run(i).current).toMatchObject({participation:{roster:0,reviewers:0,percentage:null},medianFirstReviewMs:null,usefulReviews:0})})
})
