import {describe,it,expect} from "vitest"
import {createSeasonEntry,createSeasonSnapshot,sampleSeasonTimeline,type SeasonDefinition} from "./snapshot.ts"
import type {StandingsInput} from "../standings/v1.ts"
const definition:SeasonDefinition={id:"2026-09",version:1,name:"Example season",scoringPolicyVersion:"v1",themePack:{id:"example",version:"1",assetBaseUrl:"/example",integrity:"fixture"},progressPolicy:{version:"1",individualTargetPoints:200,teamTargetPointsPerStartingParticipant:200,lateJoinFloor:.25,milestones:[{id:"quarter",scope:"participant",threshold:.25},{id:"half",scope:"participant",threshold:.5},{id:"team_half",scope:"team",threshold:.5}]}}
function input():StandingsInput{return {organizationId:"org",seasonId:"2026-09",eligibleFrom:"2026-09-07T12:00:00Z",pendingPullRequests:0,participants:[{id:"p",displayName:"Person",avatarUrl:null,eligible:true,active:true,joinedAt:"2026-09-07T12:00:00Z",leftAt:null}],components:[{id:"component",organizationId:"org",seasonId:"2026-09",participantId:"p",pullRequestId:"pr",pullRequestNumber:1,pullRequestUrl:"https://github.com/t/r/pull/1",reviewId:"review",reviewOutcome:"approved",occurredAt:"2026-09-10T12:00:00Z",kind:"approval",points:8,explanation:"Earned",sourceReference:"review",scoringPolicyVersion:"v1",status:"effective"}]}}
const snapshot=(i=input(),at="2026-09-28T12:00:00Z")=>createSeasonSnapshot(i,definition,createSeasonEntry(i,definition.progressPolicy),at)
describe("PP-045 generic snapshots",()=>{
 it("composes generic standings and progress without changing points",()=>{expect(snapshot().participants[0]).toMatchObject({points:8,rank:1,status:"active",progress:{normalized:.04,targetPoints:200},scoreComponents:[{points:8}]});expect(snapshot().team.progress?.normalized).toBe(.04)})
 it("maps the same progress to racing, gardening and construction",()=>{const p=snapshot().participants[0]!.progress;expect({trackPosition:p.normalized,plantGrowth:p.normalized,constructionCompletion:p.normalized}).toEqual({trackPosition:.04,plantGrowth:.04,constructionCompletion:.04})})
 it("caps visual progress and awards generic milestones without capping score",()=>{const i=input();i.components[0]!.points=240;expect(snapshot(i).participants[0]).toMatchObject({points:240,progress:{normalized:1,reachedMilestoneIds:["half","quarter"]}})})
 it("locks a prorated team target despite later roster additions",()=>{const i=input();i.eligibleFrom="2026-09-21T12:00:00Z";const entry=createSeasonEntry(i,definition.progressPolicy);expect(entry.teamProgressTargetPoints).toBe(100);i.participants.push({...i.participants[0]!,id:"late",joinedAt:"2026-09-22T12:00:00Z"});expect(createSeasonSnapshot(i,definition,entry,"2026-09-28T12:00:00Z").team.progress?.targetPoints).toBe(100)})
 it("applies the authored late-join floor and handles zero starting roster",()=>{const i=input();i.eligibleFrom="2026-10-05T11:00:00Z";expect(createSeasonEntry(i,definition.progressPolicy).teamProgressTargetPoints).toBe(50);i.participants=[];expect(createSeasonEntry(i,definition.progressPolicy).teamProgressTargetPoints).toBeNull()})
 it.each([["2026-09-01T00:00:00Z","scheduled"],["2026-09-07T12:00:00Z","active"],["2026-10-02T12:00:00Z","final_stage"],["2026-10-05T12:00:00Z","finalizing"]])("uses deterministic lifecycle at %s",(at,state)=>expect(snapshot(input(),at).lifecycleState).toBe(state))
 it("requires explicit finalization for championship achievements",()=>{const i=input(),entry=createSeasonEntry(i,definition.progressPolicy);expect(snapshot(i,"2026-10-05T12:00:00Z").participants[0]!.achievementIds).toEqual([]);expect(createSeasonSnapshot(i,definition,entry,"2026-10-05T12:00:00Z",{finalized:true}).participants[0]!.achievementIds).toEqual(["champion"])})
 it("samples corrected daily history without future awards or invented health",()=>{const i=input(),entry=createSeasonEntry(i,definition.progressPolicy),samples=sampleSeasonTimeline(i,definition,entry,"2026-09-11T12:00:00Z");expect(samples[0]!.participants[0]!.points).toBe(0);expect(samples.at(-1)!.participants[0]!.points).toBe(8);expect(samples.every(s=>s.health===null&&s.historyBasis==="current_corrected_ledger")).toBe(true);expect(sampleSeasonTimeline(i,definition,entry,"2026-09-01T12:00:00Z")).toEqual([])})
 it("preserves deterministic output and input",()=>{const i=input(),copy=structuredClone(i);expect(snapshot(i)).toEqual(snapshot(i));expect(i).toEqual(copy)})
 it("rejects invalid targets and mismatched scope",()=>{const i=input();expect(()=>createSeasonEntry(i,{...definition.progressPolicy,individualTargetPoints:0})).toThrow("target");expect(()=>createSeasonSnapshot(i,definition,{...createSeasonEntry(i,definition.progressPolicy),organizationId:"other"},"2026-09-28T12:00:00Z")).toThrow("scope")})
})
