import {describe,it,expect} from "vitest"
import {recommendNextReview,type RecommendationInput} from "./v1.ts"
function input():RecommendationInput{return {organizationId:"org",participant:{id:"p",githubUserId:2,eligible:true,active:true},accessibleRepositoryIds:["repo"],candidates:[{id:"pr",organizationId:"org",repositoryId:"repo",url:"https://github.com/team/repo/pull/1",authorGithubUserId:1,authorEligible:true,open:true,draft:false,selected:true,readyAt:"2026-09-25T12:00:00Z",waitingForAuthor:false,reviewerGithubIds:[],priorReviewerCount:0,repositoryUsefulReviews:2,gate:{credit:"required",observedAt:"2026-09-28T11:59:00Z",unchanged:true}}]}}
const run=(i:RecommendationInput)=>recommendNextReview(i,"2026-09-28T12:00:00Z")
describe("PP-044 recommendations",()=>{
 it("returns a GitHub link and machine-readable reasons",()=>{expect(run(input())).toMatchObject({pullRequestId:"pr",url:"https://github.com/team/repo/pull/1",reasons:[{code:"aging_pr"},{code:"repository_coverage"},{code:"review_needed"}]})})
 it.each(["self","ineligible","inactive","draft","closed","author","repository","access","reviewed","author_wait","unknown","satisfied","stale","changed","fallback_full","bad_url"])("excludes %s",reason=>{const i=input(),c=i.candidates[0]!;switch(reason){case"self":c.authorGithubUserId=2;break;case"ineligible":i.participant.eligible=false;break;case"inactive":i.participant.active=false;break;case"draft":c.draft=true;break;case"closed":c.open=false;break;case"author":c.authorEligible=false;break;case"repository":c.selected=false;break;case"access":i.accessibleRepositoryIds=[];break;case"reviewed":c.reviewerGithubIds=[2];break;case"author_wait":c.waitingForAuthor=true;break;case"unknown":c.gate=null;break;case"satisfied":c.gate!.credit="satisfied";break;case"stale":c.gate!.observedAt="2026-09-28T11:54:59Z";break;case"changed":c.gate!.unchanged=false;break;case"fallback_full":c.gate!.credit="unconfigured";c.priorReviewerCount=2;break;case"bad_url":c.url="https://evil.example/pr"}expect(run(i)).toBeNull()})
 it("allows the second fallback reviewer without freeing dismissed occupied slots",()=>{const i=input();i.candidates[0]!.gate!.credit="unconfigured";i.candidates[0]!.priorReviewerCount=1;expect(run(i)).not.toBeNull();i.candidates[0]!.priorReviewerCount=2;expect(run(i)).toBeNull()})
 it("prioritizes aging, then repository coverage, then oldest ready PR",()=>{const i=input();const base=i.candidates[0]!;i.candidates.push({...base,id:"less_covered",repositoryUsefulReviews:0,readyAt:"2026-09-26T12:00:00Z"},{...base,id:"fresh",repositoryUsefulReviews:0,readyAt:"2026-09-28T11:00:00Z"});expect(run(i)?.pullRequestId).toBe("less_covered");expect(run({...i,candidates:[...i.candidates].reverse()})).toEqual(run(i))})
 it("fails closed on future observations and missing readiness",()=>{const i=input();i.candidates[0]!.gate!.observedAt="2026-09-28T12:01:00Z";expect(run(i)).toBeNull();i.candidates[0]!.readyAt=null;expect(run(i)).toBeNull()})
 it("rejects mixed organization candidates",()=>{const i=input();i.candidates[0]!.organizationId="other";expect(()=>run(i)).toThrow("Cross-organization")})
})
