import type { ReactNode } from 'react'
function Document({ title, children }: { title: string; children: ReactNode }) {
  return <main className="mx-auto max-w-2xl px-6 py-12 leading-relaxed">
    <a className="text-sm underline" href="/sign-in">Back to your account</a>
    <h1 className="mt-5 text-3xl font-semibold">{title}</h1>
    <p className="mt-3 text-sm text-text-faint">Private pilot · Updated September 29, 2026</p>
    <p className="mt-2 text-sm text-text-faint">Operator: Pull Prix</p>
    <div className="mt-8 space-y-8">{children}</div>
  </main>
}
function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section><h2 className="mb-3 text-xl font-semibold">{title}</h2><div className="space-y-3">{children}</div></section>
}
export function PilotContact() {
  return <p>For support, privacy questions, or a deletion request, contact Patrick, who handles support and privacy requests for Pull Prix, using your private pilot onboarding conversation. Include your GitHub organization name and the type of request. Do not send passwords, access tokens, or private repository content.</p>
}
export function PrivacyPage() {
  return <Document title="Privacy policy">
    <Section title="Who this covers"><p>Pull Prix is a founder-operated private pilot that turns GitHub review activity into team standings. This policy covers our pilot website, sign-in, and GitHub integration. Your organization chooses whether to install Pull Prix and which repositories to connect.</p><PilotContact /></Section>
    <Section title="Information we receive"><p>GitHub sign-in and our authentication provider supply your GitHub ID, login, avatar, and account details, which may include an email address. We use sign-in sessions to identify you and check your access.</p><p>For connected organizations and selected repositories, we receive organization and repository identifiers and names, installation and permission information, participant identities, pull-request titles and links, authors, timestamps, review states, reviewer requests, and review/comment metadata. Raw webhook payloads and review-comment records can contain written comments, PR descriptions, file paths, or code excerpts included by GitHub.</p><p>We do not clone repositories or fetch source files to score reviews. Access to repository contents permission is used for branch and review-rule metadata. GitHub payloads may nevertheless contain code excerpts. We also keep derived scores, standings, streaks, review-health information, saved season results, and operational records needed to run and troubleshoot the service.</p></Section>
    <Section title="How we use and share information"><p>We use this information to authenticate users, check team access, import review activity, calculate and explain scores, display team results, repair processing errors, and support the pilot. A 60-day activity lookback identifies participants; it does not award points for activity before the team's scoring start.</p><p>Authorized team viewers can see team standings and review-health information, including other participants' GitHub identities. A team viewer may see team-level information even when GitHub does not grant that person access to every linked repository. Opening a private PR still requires permission in GitHub. Standings are not public.</p><p>Pull Prix operators may access data to provide support, investigate problems, and fulfill privacy requests. We do not sell personal information or use it for advertising. We may disclose information when required by law or necessary to address abuse or protect the service.</p></Section>
    <Section title="Service providers and browser storage"><p>Vercel provides website hosting. Supabase provides the hosted database, authentication, and backend functions. GitHub provides sign-in, installation permissions, review data, and avatars. These services also process connection and security information under their own policies. See <a className="underline" href="https://vercel.com/legal/privacy-policy">Vercel's privacy policy</a>, <a className="underline" href="https://supabase.com/privacy">Supabase's privacy policy</a> and <a className="underline" href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub's privacy statement</a>.</p><p>The app stores its session and sign-in return information in your browser tab's session storage. GitHub and Supabase may use their own authentication cookies or storage. The pilot does not add advertising trackers.</p></Section>
    <Section title="Retention and deletion"><p>We retain connected-team records, including review payloads and completed seasons, while the organization uses the pilot. Completed results remain fixed for sporting purposes, but are removed when the team's data is deleted.</p><p>Uninstalling the last Pull Prix installation for an organization stops further processing once the uninstall is received and applied. The next successful deletion maintenance run removes the organization's stored team data, raw webhook payloads, and queued work. Our operational target is within 24 hours; failed processing requires operator follow-up. If a replacement installation remains connected, uninstalling an old installation does not erase the active team's history.</p><p>An organization administrator may request deletion through pilot support. We verify authority before deleting the team's data. After deletion, the existing installation cannot resume collecting data; a deliberate new installation starts fresh. Deletion from Pull Prix does not delete anything in GitHub.</p><p>We retain a minimal deletion record: an opaque organization reference, deletion reason and timestamp, and GitHub account/installation IDs needed to reject delayed events. This record contains no PR, review, repository-name, or score content. It is retained to prevent deleted data from being recreated.</p><p>A person's sign-in account and identity used by another connected team are not deleted with one organization. Ask support separately for personal-data access, correction, or account deletion. Privacy requests are distinct from ordinary game preferences; the pilot does not offer a hide-my-score setting.</p><p>Restricted operational logs and any recovery copies may persist separately until their applicable retention ends. They are not used to repopulate the active service after deletion. Before any restore, we reapply deletion records. Contact us for the retention details applicable to your request; we do not promise instantaneous erasure from every provider backup.</p></Section>
    <Section title="Your choices and policy changes"><p>Your organization can change selected repositories or uninstall through GitHub. Removing a repository stops new collection from it; it does not itself erase the team's earlier season results. You may sign out at any time. Contact pilot support to exercise applicable privacy rights or discuss information we hold about you.</p><p>We will notify pilot contacts of material changes and update the date on this page. New hosting or data-processing providers will be disclosed before being introduced to the pilot.</p></Section>
  </Document>
}
export function TermsPage() {
  return <Document title="Pilot terms">
    <Section title="The pilot"><p>These terms govern your use of Pull Prix's private pilot. By using the service, you agree to these terms. Pull Prix is an experimental, founder-supported service for professional teams. You must be at least 18 and authorized to connect any organization or repositories you install it on. Your organization is responsible for informing its team about the integration and its visible standings.</p></Section>
    <Section title="Access and acceptable use"><p>Use your own GitHub account and keep it secure. Only access organizations you are authorized to view. Do not bypass access controls, interfere with the service, expose another team's private data, or manufacture activity to manipulate scores. We may restrict access to address abuse, security problems, or loss of GitHub permissions.</p></Section>
    <Section title="What scores mean"><p>Scores describe qualifying review activity under the published scoring rules. They do not measure overall engineering performance, review quality, or a person's value. Do not use standings as the sole basis for employment or compensation decisions. Data can arrive late, be incomplete, or require correction. Tell pilot support if a result appears wrong.</p><p>Seasons follow the shared calendar automatically. Ordinary GitHub changes do not rewrite finalized results; documented support corrections and privacy deletion may affect saved results. The service offers no cash prizes or guaranteed rewards.</p></Section>
    <Section title="Your data"><p>You retain your rights in your organization's content. You authorize Pull Prix and its service providers to process connected data only as needed to operate, secure, and support the service as described in the <a className="underline" href="/privacy">privacy policy</a>. This does not transfer ownership of your repositories or reviews. You are responsible for having authority to provide the connected data.</p></Section>
    <Section title="Availability and ending the pilot"><p>The pilot is provided as available, without a guaranteed uptime or uninterrupted service. Features and scoring versions may change; we will communicate material changes to pilot contacts. GitHub and other providers may also limit availability. No payment obligation is created by these pilot terms; any future paid offering requires a separate agreement.</p><p>You may stop using the service and your organization may uninstall at any time. We may end the pilot or suspend access, with notice when practical. Team deletion and retained security records follow the privacy policy. Nothing in these terms excludes rights or responsibilities that applicable law does not allow us to exclude.</p></Section>
    <Section title="Questions and support"><PilotContact /></Section>
  </Document>
}
